name: Go fuzz test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-suite:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup Golang
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613
        with:
          go-version: '1.19'

      - name: Fuzz test
        run: |
          GO111MODULE=on go mod tidy
          GO111MODULE=on go mod vendor
          ./tools/fuzz-all.sh 30
